groups:
  - name: nginx_alerts
    rules:
      - alert: NginxDown
        expr: up{job="nginx"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Nginx est arrêté"
          description: "Le serveur nginx n'est plus accessible depuis {{ $labels.instance }}"

      - alert: NginxHighErrorRate
        expr: rate(nginx_http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Taux d'erreur nginx élevé"
          description: "Le taux d'erreur 5xx est élevé sur {{ $labels.instance }}"

      - alert: NginxHighResponseTime
        expr: histogram_quantile(0.95, rate(nginx_http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Temps de réponse nginx élevé"
          description: "95% des requêtes prennent plus d'1 seconde sur {{ $labels.instance }}"

  - name: system_alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Utilisation CPU élevée"
          description: "L'utilisation CPU est supérieure à 80% sur {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Utilisation mémoire élevée"
          description: "L'utilisation mémoire est supérieure à 85% sur {{ $labels.instance }}"

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Utilisation disque élevée"
          description: "L'utilisation disque est supérieure à 85% sur {{ $labels.instance }}"

      - alert: NodeExporterDown
        expr: up{job="node-exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Node Exporter arrêté"
          description: "Node Exporter n'est plus accessible sur {{ $labels.instance }}"

  - name: prometheus_alerts
    rules:
      - alert: PrometheusDown
        expr: up{job="prometheus"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Prometheus est arrêté"
          description: "Prometheus n'est plus accessible"

      - alert: PrometheusHighScrapeErrors
        expr: rate(scrape_samples_post_metric_relabeling_failed_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Erreurs de scraping Prometheus"
          description: "Prometheus rencontre des erreurs lors de la collecte de métriques" 